### ISSUE TITLE
Enable Emblem Hover BG for old clients [BUG]

### ISSUE THREAD

**Issue by cassioronchetti** [Neo-Mind/WARP#1]
**Describe the bug**

I use 2010-07-30 Client and I can't enable this patch to show BG emblem over the head to play Battleground. 

**To Reproduce**

There isn't the option to try this patch for old clients.

**Expected behavior**

Would be great to have this patch to enable emblem over head for Battlegrounds for old clients  2010 to 2012 clients because a lot of people use old clients to play pre-re server instead of using new clients and the Battleground is one of the best thing to do on Ragnarok on pre-renewal servers.

**Comment by Neo-Mind** [comment]
I'll have a look at this.

**Comment by cassioronchetti** [comment]
Nice to hear that!! I want this one so badly! I will help you to find other issues until them.

**Comment by cassioronchetti** [comment]
Any updade on this?

**Comment by Neo-Mind** [comment]
@cassioronchetti can you try out the patch. I have made some changes.
You might need to do a @refresh once you're on the map.

**Comment by cassioronchetti** [comment]
Didn't work, I tried on 2010-07-30aRagexe which is the most used client for pre-renewal classic server in my country.

**Comment by Neo-Mind** [comment]
@cassioronchetti Try it now. You would need to refresh once you are on the map.
To fix this part, you would need to send the map flag before the idle packet is sent. 

(20121010 onwards a different packet is used, hence this problem doesn't arise).

Btw I heard from Ai4rei that the dates between (but not including) 2010-07-28RE & 2010-08-04RE are defective.

**Comment by cassioronchetti** [comment]
It's working like a charm!! Congratulations Neo!! I wish I had this knowledge to do these kinds of things!!

You also fixed the emblem alignment from this issue https://github.com/Neo-Mind/NEMO/issues/86.

Well done! Btw is it possible to follow you on instagram or facebook? I am a big fan of your work!

**Comment by cassioronchetti** [comment]
It's working like a charm!! Congratulations Neo!! I wish I had this knowledge to do these kinds of things!!

Well done! Btw is it possible to follow you on instagram or facebook? I am a big fan of your work!

**Comment by Neo-Mind** [comment]
OK, gr8. Well, I am there at discord and I recently joined twitch (haven't really used it much though). 
https://www.twitch.tv/NeoMnd

Anyways I am closing this issue now :)

**Comment by Neo-Mind** [comment]
@cassioronchetti Are you still facing issues with the patch?

**Comment by cassioronchetti** [comment]
Hello Neo! I have the issue about @refresh to display the emblem, because I don't know how to send the map flag before the idle packet is sent.

Another issue you can see in the screenshot below. When you leave the screen from your enemies the emblem doesn't disappear, it stays in the screen while you are walking on the map. (using 2010-07-30aRagexeRE)

Another thing I noticed is that by fixing this patch for old clients, it suddently broke the same patch for new clients. I was testing it on 2018-04-18 and it wasn't working. I think one solution would be making two patches, one that works on old clients and one for new clients. 

![screenHercules032](https://user-images.githubusercontent.com/46929230/110982255-139e7300-8347-11eb-8f3a-5d65bb599586.jpg)

![screenHercules033](https://user-images.githubusercontent.com/46929230/110983776-f4084a00-8348-11eb-94cc-1b239d55efb4.jpg)

**Comment by Neo-Mind** [comment]
Thanks for waiting. All the fixes have been pushed. Please check and let me know.

As I stated before, all clients >= 20121010 have a separate packet that indicates the BG mapflag (along with others).
The client sets up the icon in response to this packet.

In older clients, the mapflag is checked after an idle packet is sent.
So in your server, while changing maps, you need to set the mapflag first and then send the idle packet.

It would be best to discuss that part in the server forum.

**Comment by cassioronchetti** [comment]
It's working fine in new clients!
