### ISSUE TITLE
[BUG] Customize Captcha Decomp size malfunctioning

### ISSUE THREAD

**Issue by Neo-Mind** [Neo-Mind/WARP#100]
**Describe the bug**
Customize Captcha Decomp size messes up the image - Reported by @Pokye and @HnomkenG

**Screenshots**
![error](https://media.discordapp.net/attachments/780647066871136269/1002375879705497610/unknown.png)

**Comment by Neo-Mind** [comment]
Fixed in local . Will be pushed soon.

**Comment by Neo-Mind** [comment]
Check it now.

**Comment by hnomkeng** [comment]
Will test on night.

**Comment by Neo-Mind** [comment]
Closing this since the issue is already being tracked [here](https://github.com/Neo-Mind/WARP/issues/103)
