### ISSUE TITLE
[BUG] Fix Allow Spam Skills by Hotkey

### ISSUE THREAD

**Issue by LadyNanuia** [Neo-Mind/WARP#102]
**Describe the bug**
It no longer works, it used to

**To Reproduce**
3. See error

**Expected behavior**
The patch would let you hold down a button in order to spam a skill if it was applied within the server settings of course, sadly it doesnt work for a while now, i reported it a long time ago but no fix since sadly so im trying here.

**Screenshots**

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 - Tool Feature
 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by Neo-Mind** [comment]
Fixed in local. Will be pushed soon.

**Comment by Neo-Mind** [comment]
Check it now.

**Comment by Neo-Mind** [comment]
Closing this since you opened another [issue](https://github.com/Neo-Mind/WARP/issues/108) for it
