### ISSUE TITLE
[BUG] Move Cash Shop Icon make client crash when loading map after char select

### ISSUE THREAD

**Issue by SapitoSucio** [Neo-Mind/WARP#107]
**Describe the bug**
As the title says, activating this patch using any value will make the client crash after char select, it doesn't pops the bugsplat windows, it just closes

**To Reproduce**
Using Warp, apply Move Cash Shop Icon patch using any values
Start the Client, login and select char, the game will close mid loading

**Expected behavior**
The Shop Icon should be on the wanted coords

**Additional Details (Complete all relevant items below)**
- Client: 20211103
- Patch: Move Cash Shop Icon

**Comment by Neo-Mind** [comment]
Fixed in local. Will be pushed soon.

**Comment by Neo-Mind** [comment]
Please check if it's a problem now.

**Comment by SapitoSucio** [comment]
> Please check if it's a problem now.

It's fixed now 😺
![image](https://user-images.githubusercontent.com/7357354/192090580-ff8b807a-4791-4f38-b816-6eda9d68ed51.png)
