### ISSUE TITLE
[BUG] Patchs in client 2022-03-30 / 2022-04-06

### ISSUE THREAD

**Issue by Pokye** [Neo-Mind/WARP#109]
**Describe the bug**
Some patches are in error on client **2022-03-30 / 2022-04-06**.

http://ropatch.gnjoy.com/Patch/2022-03-30_Ragexe_1648440293.rgz
http://ropatch.gnjoy.com/Patch/2022-04-06_Ragexe_1648707856.rgz

**Screenshots**

**Enable item preview in Cash Shop**
![image](https://user-images.githubusercontent.com/98105181/189411755-60b2a893-74ca-40be-9a6b-8d49c0de8887.png)
![image](https://user-images.githubusercontent.com/98105181/189411794-91a627bc-97a0-4091-90ac-f465d0f7e542.png)

**Enable Custom Jobs**
![image](https://user-images.githubusercontent.com/98105181/189412137-87387ceb-c7f5-4ff6-a3e4-781c8c6d0d9a.png)

**Always see hidden/cloaked objects**
![image](https://user-images.githubusercontent.com/98105181/189412304-1a72fbf4-1c6f-428c-a8c6-f34019a8bd79.png)

**Remove Hourly announcement**
![image](https://user-images.githubusercontent.com/98105181/189412682-91913575-372d-48e1-8760-0608ee1b1524.png)

**Resize NPC Dialog Box**
![image](https://user-images.githubusercontent.com/98105181/189412806-4897add9-e27f-4413-84e5-f6eac4e15164.png)

**Comment by kreanlnwza** [comment]
[Neo-Mind]
skip signboard [BUG] Patchs in client 2022-03-30 / 2022-04-06 not run exe
and unlimitedchat
![image](https://user-images.githubusercontent.com/59070443/190238062-b87336e5-bac8-46e7-b17a-894ebde6d900.png)

**Comment by hnomkeng** [comment]
> [Neo-Mind] skip signboard [BUG] Patchs in client 2022-03-30 / 2022-04-06 not run exe and unlimitedchat ![image](https://user-images.githubusercontent.com/59070443/190238062-b87336e5-bac8-46e7-b17a-894ebde6d900.png)

confirm

**Comment by SapitoSucio** [comment]
Client: 20220330
Patch: Increase Hairstyles
![image](https://user-images.githubusercontent.com/7357354/191582857-1f28e8d5-da48-414d-85f4-740c5036d361.png)

**Comment by Neo-Mind** [comment]
Check them now.

**Comment by Pokye** [comment]
If you increase the size of the gif the client does not open.
![image](https://user-images.githubusercontent.com/98105181/192093637-77dcd2b5-3878-4aff-bb10-4417fb2ff58b.png)
![image](https://user-images.githubusercontent.com/98105181/192093648-654d89d1-2e5a-4b30-bbeb-e2580a3ee831.png)
![image](https://user-images.githubusercontent.com/98105181/192093666-7f666ce3-517b-4eb6-afa7-d357b9b92442.png)

The other diff, applied without error, but I'm still going to test them all

**Comment by Neo-Mind** [comment]
Fixed that

**Comment by Pokye** [comment]
Working now...

**Comment by Neo-Mind** [comment]
Saw any other problems?

**Comment by Pokye** [comment]
So far no, I'm using all the diffs I mentioned that were having a problem, and they're working fine now.

**Comment by SapitoSucio** [comment]
> Saw any other problems?

I activated the Customize ClientInfo file, applied 'sclientinfo.xml' as value and the client would not seem to find it. Having both sclientinfo and clientinfo in the data folder

**Comment by Neo-Mind** [comment]
> > Saw any other problems?
> 
> I activated the Customize ClientInfo file, applied 'sclientinfo.xml' as value and the client would not seem to find it. Having both sclientinfo and clientinfo in the data folder

Is it still happening @SapitoSucio . I am not seeing the issue at my end.

**Comment by SapitoSucio** [comment]
I'll check it when I get home 🏠

**Comment by SapitoSucio** [comment]
> > > Saw any other problems?
> > 
> > 
> > I activated the Customize ClientInfo file, applied 'sclientinfo.xml' as value and the client would not seem to find it. Having both sclientinfo and clientinfo in the data folder
> 
> Is it still happening @SapitoSucio . I am not seeing the issue at my end.

I just tested it, having both client & sclient info files on my data folder, when I apply the patch to read sclientinfo.xml I get this message the moment the client opens 
![image](https://user-images.githubusercontent.com/7357354/197673094-623e2d11-b63a-480f-8170-adf02dd0170c.png)


I notice that even the font changes

**Comment by Neo-Mind** [comment]
Can you tell me which patches you use? I am not seeing that problem.

**Comment by SapitoSucio** [comment]
> Can you tell me which patches you use? I am not seeing that problem.

Here is my session file 
[session.zip](https://github.com/Neo-Mind/WARP/files/9866678/session.zip)

**Comment by Neo-Mind** [comment]
> > Can you tell me which patches you use? I am not seeing that problem.
> 
> Here is my session file [session.zip](https://github.com/Neo-Mind/WARP/files/9866678/session.zip)

I don't see the patch selected in the session file. 
I see that you have set the input for it but the patch is not there.

**Comment by SapitoSucio** [comment]
> > > Can you tell me which patches you use? I am not seeing that problem.
> > 
> > 
> > Here is my session file [session.zip](https://github.com/Neo-Mind/WARP/files/9866678/session.zip)
> 
> I don't see the patch selected in the session file. I see that you have set the input for it but the patch is not there.

Mmm well, that's really strange, let me re do it

**Comment by SapitoSucio** [comment]
https://user-images.githubusercontent.com/7357354/198986471-9c216787-a35e-465b-a1a6-a72f355221b5.mp4
