### ISSUE TITLE
[BUG] Enable item preview in Cash Shop

### ISSUE THREAD

**Issue by Juliando2020** [Neo-Mind/WARP#111]
**Describe the bug**
 - Enable item preview in Cash Shop
 - not work in hexed 20220331

![Sem título](https://user-images.githubusercontent.com/102198193/189717629-4ec438c4-fea9-43ff-9857-f94d58514ae9.png)

**Comment by kreanlnwza** [comment]
Your server is up and running.  Have ExtendCashShopPreview installed? You need to diff exe accordingly.

**Comment by Juliando2020** [comment]
yes is active  
![image](https://user-images.githubusercontent.com/102198193/189754217-96b5b005-44dd-4dc3-9e0a-44dc3a6b5c50.png)

**Comment by kreanlnwza** [comment]
If enabled please diff exe on the same topic as well.

**Comment by Neo-Mind** [comment]
Will be fixed along with other issues [reported for 2022-03 clients](https://github.com/Neo-Mind/WARP/issues/109)

**Comment by Neo-Mind** [comment]
Check it now.

**Comment by Neo-Mind** [comment]
I will be closing this one tomorrow. If the problem is still there, then please reopen
