### ISSUE TITLE
[BUG] Customize Max Emblem File Size Patch corrupts the final exe

### ISSUE THREAD

**Issue by SapitoSucio** [Neo-Mind/WARP#112]
**Describe the bug**
Customize Max Emblem File Size corrupts the final client

**To Reproduce**
1. Activate the Customize Max Emblem File Size patch with any values 
2. Build Client
3. Try to run

**Expected behavior**
Client should open when executed 

**Screenshots**
![image](https://user-images.githubusercontent.com/7357354/192090778-73ff0719-e1ed-4635-9297-026fc582d751.png)

Trying to open the exe popups a ms windows saying that this application cant be executed on this machine

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name: Customize Max Emblem File Size
 - Build Dates affected 2021-11-03
 - OS: Windows

**Comment by Neo-Mind** [comment]
Fixed
