### ISSUE TITLE
[BUG] Custom Lua Support makes client show Lua Error

### ISSUE THREAD

**Issue by SapitoSucio** [Neo-Mind/WARP#113]
**Describe the bug**
  Custom Lua Support patch make client to show lua error

**To Reproduce**
  1. Activate llChrisll Custom Lua Support Patch and patch client
  2. Download latest Custom Lua Support files from llchrisll repo and place the files
  3. Run Client and error will appera

**Expected behavior**
Client should open without problems

**Screenshots**
![image](https://user-images.githubusercontent.com/7357354/193134385-d0210ade-9aff-4e46-a511-d810c15f0f09.png)
![image2](https://user-images.githubusercontent.com/7357354/193134641-87440f15-66db-4675-bc53-52b0c76412d1.png)

**Additional Details (Complete all relevant items below)**
 - Custom Lua Support Patch
 - Client: 20220330
 - Windows

**Comment by Neo-Mind** [comment]
Fixed.
