### ISSUE TITLE
[BUG] 2019-05-30a ragexe

### ISSUE THREAD

**Issue by MrKeiKun** [Neo-Mind/WARP#114]
**Describe the bug**
Below patches after years of working, decided to not work on my test just now.
>IncrViewID
> CustomClientInfo
> NoEquipPreview
> CustomNewCharNameHeight

**Additional Details (Complete all relevant items below)**
 - Warp Version: ab3ca44ba373faa738dd89fb4eb1f57bebb1a30f
 - Client: 2019-05-30a Ragexe
 - OS: Windows 10 21H2

**Comment by Neo-Mind** [comment]
I am not seeing the issue. Are you sure you are using an unmodified client?

**Comment by MrKeiKun** [comment]
@Neo-Mind oh my god. how is that even possible. closing this, thanks man. i have to redownload the client again even if its versionized on download as well as using it.
