### ISSUE TITLE
[BUG] Moving the Directory of WARP causes an error

### ISSUE THREAD

**Issue by Gladdle** [Neo-Mind/WARP#12]
If you start WARP in a Directory, then move it will cause an error. I have executed it under Windows 7 Pro 64bit, first in 
D:\Programs\Ragnarok-p-Server-Tools\WARP\WARP.EXE
And then i make a Folder for the Version Number and move ALL Files in there:
D:\Programs\Ragnarok-p-Server-Tools\WARP\Version-1.2.1\WARP.EXE
Because sometimes newer Version will have an Bug so i use the old ones. But when i try to use this tool that error appears"
--------------------
TOOL ERROR
'D:/Programs/Ragnarok-p-Server-Tools/WARP/Patches.yml' is inaccessible
--------------------
Is there anywhere a Configuration saved, in %appdata% or the Registry? Maybe a Button to reset may be cool AND a link to this page if you search for a newer version.

**Comment by Neo-Mind** [comment]
The exe files expect DLLs in the same directory and all the scripts & YAML files will be in the parent folder.
I made the hierarchy this way so that I can enable usage in other OS too (For e.g. I have added the Debian version).

Which bug are you facing with the tool?

**Comment by Gladdle** [comment]
No, i've copied _ALL_ Files in that Directory (D:\Programs\Ragnarok-p-Server-Tools\WARP\Version-1.2.1\).
If i start WARP than i add The Path from the ragexe (WITH the ragexe.exe) to the "Source" Field. In the Output field nearly the same, but another .exe Name (Patched.exe). If i press the Button "Load Source" the Error appear. He doesn't search for a "DLL" file, they are all in the Directory, he is searching for the File "Patches.yml".

EDIT: There is a file called D:\Programs\Ragnarok-p-Server-Tools\WARP\Settings.yml
But the error still appears. The file system for this drive is NTFS.

**Comment by Neo-Mind** [comment]
First of all, I would not suggest doing a copy of the older versions, unless you are keeping all the files at a specific commit. Would be great if you could post a Github issue if you faced any bug with the latest version.

Anyways, I will try explaining this again. This is the hierarchy expected.

```
Tool Folder
- Scripts/
- Inputs/
- Outputs/
- Patches.yml
- Extensions.yml
- etc.
- Sub Directory/
       - WARP.exe
       - GATE.dll
       - other dlls from Qt.
```
There is no restriction on the Sub Directory's name. I keep it as an indicator of which OS the tool was compiled for.
For e.g. 
win32 means Windows 32 bit (which also works for 64 bit systems)
deb32 means Debian 32 bit (but it can possibly work for other 32 bit Linux systems).

Now if you are sure that you are keeping this same hierarchy, then this is definitely an issue.

**Comment by Neo-Mind** [comment]
@Gladdle is it ok now? Shall I close?

If you are facing some issue with the tool itself then please post a separate issue about it.

**Comment by Neo-Mind** [comment]
Closing the issue since no response for more than a week.
