### ISSUE TITLE
[BUG] Enable Multiple GRF (Embedded)

### ISSUE THREAD

**Issue by Pokye** [Neo-Mind/WARP#128]
**Describe the bug**
When using this patch on 2022+ clients it creates a data.grf with 0 bytes. as if it were mandatory to use data.grf even if I set it to another name.

\WARP\Inputs\DATA.INI
```
[data]
0=data1.grf
1=data2.grf
```
Tested on clients 2022-04-06, 2022-06-07, 2022-12-07 and 2023. and using the latest version of WARP

**Screenshots**
![image](https://github.com/Neo-Mind/WARP/assets/98105181/b4e80580-8df0-4cb8-b49b-388dacf25c11)
![image](https://github.com/Neo-Mind/WARP/assets/98105181/cf60ffcc-198f-45bf-b5fa-1807cef46533)

**Comment by Daegaladh** [comment]
~Same thing happens using 2021-11-03~
Doesn't work at all, even with just the recommended patches, both embedded or external, doesn't read the data.ini at all

**Comment by gidzdlcrz** [comment]
Same thing happened if we dont use that patch. It will create a blank 'DATA' folder in your RO directory. Maybe thats why its creating data.grf with 0 bytes.

**Comment by Daegaladh** [comment]
This seems to have been fixed already
