### ISSUE TITLE
Add case-insensitive cash shop search patch  

### ISSUE THREAD

**Issue by patcervatos** [Neo-Mind/WARP#13]
**Is your feature request related to a problem? Please describe.**
It would be nice to have this patch like the one that you have for the storage search
**Describe the solution you'd like**
As the title implies, search would be case-insensitive.

**Additional context**

**Comment by Neo-Mind** [comment]
This will be added soon.

**Comment by Neo-Mind** [comment]
Patch has been added. Check it out.

**Comment by Neo-Mind** [comment]
Closing this, since there is no feedback. Hope it is working as intended.
