### ISSUE TITLE
Custom Inventory Limit

### ISSUE THREAD

**Issue by patcervatos** [Neo-Mind/WARP#14]
**Describe the bug**
When using the Custom Inventory Limit patch, the client shows ascii characters instead of showing the actual maximum inventory capacity.

**To Reproduce**
1. Use 2018-06-20eRagexe client to patch
2.  Select Custom Inventory Limit patch, set to 250. (I've also used 150 and 200. They show different characters)
3.  Use new patched client and check inventory.

**Expected behavior**
Show the actual maximum capacity instead of random characters.

**Screenshots**
This is what default looks like:
![image](https://user-images.githubusercontent.com/28685551/107177448-d6c02300-6a0c-11eb-9d0f-3425e3f4ed41.png)

This is what the patched client looks like:

![image](https://user-images.githubusercontent.com/28685551/107177528-fe16f000-6a0c-11eb-9cff-43b7a4da1d64.png)

![image](https://user-images.githubusercontent.com/28685551/107177810-ac229a00-6a0d-11eb-90ce-7de38c087ac9.png)

**Additional Details (Complete all relevant items below)**
 - Custom Inventory Limit
 - 1.2.0
 - Windows 10
 - Used custom fonts and font size

**Comment by Neo-Mind** [comment]
Fixed in the local version. Will be pushed soon.

**Comment by Neo-Mind** [comment]
Changes have been pushed. Check now.

**Comment by patcervatos** [comment]
thank you will check in a bit! :)

**Comment by patcervatos** [comment]
Hello! I've managed to give it a go and tested it and used 250 as max inventory capacity. Instead of showing an integer, it showed this. 
![image](https://user-images.githubusercontent.com/28685551/108003958-56fb0f80-702f-11eb-973f-eab22ec30379.png)

**Comment by patcervatos** [comment]
> Hello! I've managed to give it a go and tested it and used 250 as max inventory capacity. Instead of showing an integer, it showed this.
> ![image](https://user-images.githubusercontent.com/28685551/108003958-56fb0f80-702f-11eb-973f-eab22ec30379.png)

but 150 works fine.

![Uploading image.png…]()

**Comment by patcervatos** [comment]
Nevermind, tried it again, 250 works fine now. I wonder what happened. Hmm

![image](https://user-images.githubusercontent.com/28685551/108004313-7cd4e400-7030-11eb-86fa-43375053f318.png)


But anyway, thanks for fixing this! 💯

**Comment by Neo-Mind** [comment]
Ok, I am closing this then.
