### ISSUE TITLE
[FEATURE] Exe.Version 14 need separate between 14.16 and 14.29

### ISSUE THREAD

**Issue by X-EcutiOnner** [Neo-Mind/WARP#140]
In many patches script are use the ``switch`` like this
```javascript
    switch (Exe.Version)
    {
        case 6: //VC6
        {
            ...
        }

        case 9:  //VC9
        case 10: // to
        case 11: //VC11
        {
            ...
        }
        default: //VC14.16
        {
            ...
        }
    }
```
If we use ``Exe.BuildDate`` sometime you will write the script like this
```js
    if ((ROC.IsRenewal && Exe.BuildDate > 20230607) || (ROC.IsZero && Exe.BuildDate > 20230607))
    {
        ...
    }
```
If we use ``Exe.Version`` sometime you will write the script like this
```js
    if (Exe.Version > 14.16)
    {
        ...
    }
```
Any clients after ``2023-06-07_Ragexe_1686120134`` are ``Exe.Version`` 14.29
We should use ``Exe.BuildDate`` Or separate between ``Exe.Version`` for better maintenance or not?

**Comment by Neo-Mind** [comment]
Hi @X-EcutiOnner ,
  As mentioned here => https://github.com/Neo-Mind/WARP/wiki/Exe-Object#properties , the linker version is already split into ``Exe.Version`` and ``Exe.MinorVer``

  For 14.29, ``Exe.Version`` is **`14`** and ``Exe.MinorVer`` is **`29`**

**Comment by X-EcutiOnner** [comment]
> Hi @X-EcutiOnner , As mentioned here => https://github.com/Neo-Mind/WARP/wiki/Exe-Object#properties , the linker version is already split into `Exe.Version` and `Exe.MinorVer`
> 
> For 14.29, `Exe.Version` is **`14`** and `Exe.MinorVer` is **`29`**

I thinks it ```Exe.Version == 14.16``` can include minor version, but i know on now i can use it by ```Exe.Version == 14 && Exe.MinorVer == 16```
If ```Exe.Version == 14.16``` can include minor version is better way to shorten for coding, Thanks for the clarify.
