### ISSUE TITLE
[BUG] Enable Multiple Grf

### ISSUE THREAD

**Issue by kreanlnwza** [Neo-Mind/WARP#155]
**Describe the bug**
Using the latest WARP to test patches with the client 2024-07-04

**Screenshots**

![image](https://github.com/user-attachments/assets/d19e5bbb-b275-4610-9e73-ff50de8680a2)

**Comment by Pokye** [comment]
Commit: https://github.com/Neo-Mind/WARP/commit/a096eb66d714e141958ec7beade6cd5499295ae6

**Working!**
![image](https://github.com/user-attachments/assets/bfbea610-ac3c-4da2-8995-5a45cfe796b1)
![image](https://github.com/user-attachments/assets/445b888c-2853-40fd-a138-ec7f7730963c)

**Comment by kreanlnwza** [comment]
> Commit: [a096eb6](https://github.com/Neo-Mind/WARP/commit/a096eb66d714e141958ec7beade6cd5499295ae6)
> 
> **Working!** ![image](https://private-user-images.githubusercontent.com/98105181/358122289-bfbea610-ac3c-4da2-8995-5a45cfe796b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjkyODIsIm5iZiI6MTcyMzcyODk4MiwicGF0aCI6Ii85ODEwNTE4MS8zNTgxMjIyODktYmZiZWE2MTAtYWMzYy00ZGEyLTg5OTUtNWE0NWNmZTc5NmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzY2NkNWFlZmE1MDE0NDM4YjQzNzJiYzRiY2IzMzY3MzE0MjZkZjY3NjkzNDZiZGI0Nzk4ZWRhMmY2ZjM1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L24BGg-1cqDwZZ3um15yzD3rq6MwySEE75D0U28qX4Q) ![image](https://private-user-images.githubusercontent.com/98105181/358122442-445b888c-2853-40fd-a138-ec7f7730963c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjkyODIsIm5iZiI6MTcyMzcyODk4MiwicGF0aCI6Ii85ODEwNTE4MS8zNTgxMjI0NDItNDQ1Yjg4OGMtMjg1My00MGZkLWExMzgtZWM3Zjc3MzA5NjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTMzZmFkZGYxYjUzMzg3MGE2Yzg5ZGY3NjgyZWFhOWYyYTEyZjc5NDRjYjg5OWYzOTkwMTlmM2MxZjliYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SDo2vQTwrk33UnKH2O1hpZT0u2F1Dw7ZrmHLpPK16Fc)

Thank you for informing me. I've been very busy lately.
