### ISSUE TITLE
[BUG] Allow 65k Hair Styles

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#16]
**Describe the bug**
The client is crashing when I activate this patch on client 2021-01-07aRagexeRE, if I disable the client it opens normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/115241689-7da0f980-a0f7-11eb-9550-6a8d8d5d7819.png)

**Comment by Neo-Mind** [comment]
Fixed in local. Update will be pushed soon.

**Comment by Neo-Mind** [comment]
Pushed the fix. Please check and let me know.

**Comment by RagnaWay** [comment]
Crash the game with hair style 33 above.

Tested with "Allow 65k hair style" and "Increase hair style"

**Comment by SirHaziel** [comment]
Can confirm, same behaviour.

**Comment by Neo-Mind** [comment]
Ok i saw the crash and found the problem but I also found a different issue the hair color isn't getting set. 
Investigation in progress.

**Comment by Everade** [comment]
Can confirm the issue on 2021-01-07aRagexeRE as well.

**Comment by Neo-Mind** [comment]
@RagnaWay @Everade  @SirHaziel Pushed the update now. Please check.

I had to overhaul the entire patch, but I believe I have finally covered every table. 
On the plus side, I fixed the palettes as well and it works in tandem with Shared head palette patches properly.

**Comment by RagnaWay** [comment]
Working!

**Comment by Everade** [comment]
Did a quick test on male human only.
Works!

**Comment by Neo-Mind** [comment]
Ok I will close this then. Hopefully won't need to be reopened.
