### ISSUE TITLE
[FEATURE] Add Patch 'Add support for preview button in cash shop'

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#17]
![image](https://user-images.githubusercontent.com/53480357/115471028-b03d1600-a20d-11eb-80ea-4c558a31c197.png)
NEMO: http://nemo.herc.ws/patches/ExtendCashShopPreview/
Patch: https://gitlab.com/4144/Nemo/-/blob/master/Patches/ExtendCashShopPreview.qs
( By. Andrei Karas '4144' )

**Describe the solution you'd like**
Recently 4144 added this patch to NEMO, also deploy to WARP

**Comment by Neo-Mind** [comment]
I can look into this, but is there anything i need to configure server side?

**Comment by RagnaWay** [comment]
> I can look into this, but is there anything i need to configure server side?

this is already implemented in rA and Herc, just enable it in SRC.

rA: https://github.com/rathena/rathena/pull/5896
Herc: https://github.com/HerculesWS/Hercules/pull/2944

**Comment by RagnaWay** [comment]
@Neo-Mind any news?

**Comment by Neo-Mind** [comment]
Well Andrei has used tables for getting most of the offsets and that code is well compiled rather than scripted.
 
So I need to do some digging to find out how the tables were constructed. I dunno if he wants to keep it hidden though.

**Comment by Neo-Mind** [comment]
Added in local. Will be pushed next.

**Comment by RagnaWay** [comment]
OMG <3

**Comment by Neo-Mind** [comment]
Pushed the changes. Have a look 😄

**Comment by RagnaWay** [comment]
Working 
![image](https://user-images.githubusercontent.com/53480357/122658381-e67e0f80-d142-11eb-87c8-4ed9d560f7eb.png)
