### ISSUE TITLE
[BUG] Allow 65k hair styles

### ISSUE THREAD

**Issue by kreanlnwza** [Neo-Mind/WARP#171]
**Describe the bug**
Using the latest WARP to test patches with the client 2024-07-04

**Screenshots**
![image](https://github.com/user-attachments/assets/f8ab58fb-eca2-48f8-bcca-885b7b6f57a6)

**Comment by Pokye** [comment]
Working in https://github.com/Neo-Mind/WARP/commit/2e6a9156ea591151f2288ca0222d36498e234818
