### ISSUE TITLE
[BUG] Enable effect for all maps

### ISSUE THREAD

**Issue by kreanlnwza** [Neo-Mind/WARP#175]
**Describe the bug**
Using the latest WARP to test patches with the client 2024-07-04

**Screenshots**
![image](https://github.com/user-attachments/assets/1d38c25e-cac1-4b29-889a-4230f03a051f)

**Comment by Pokye** [comment]
Working in https://github.com/Neo-Mind/WARP/commit/2e6a9156ea591151f2288ca0222d36498e234818
