### ISSUE TITLE
[BUG] Cash Shop Unknown Items and Prices

### ISSUE THREAD

**Issue by Samuel23** [Neo-Mind/WARP#19]
**Describe the bug**
I'm using a 2019-03-22aRagexe and the cash shop looks like this:

![](https://i.imgur.com/HizEGcW.png)

**To Reproduce**
The only patch I have applied for the cash shop is:
- Use Default Web Browser in Cash Shop

I even tried to not apply it but still the same.
I tried applying other patch as well for cash shop but still the same happens.

**Expected behavior**
With Nemo:
![](https://i.imgur.com/4c9h0pM.png)

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 - Tool Feature

 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by RagnaWay** [comment]
WARP needs to add that yet.
https://github.com/Neo-Mind/WARP/issues/17

**Comment by Samuel23** [comment]
> WARP needs to add that yet.
> #17

I see thanks! So it was the preview cash shop thing. Thanks for pointing it out.

**Comment by Neo-Mind** [comment]
@Samuel23  Cash Shop preview has been added. See if the issue persists.

**Comment by Everade** [comment]
Works now. Can be closed.
