### ISSUE TITLE
Custom window Title [BUG]

### ISSUE THREAD

**Issue by cassioronchetti** [Neo-Mind/WARP#2]
**Describe the bug**

When you enable this feature and open your client, it shows the new title with some unexpected words "//ro.hangame.com/login/loginstep..."

**To Reproduce**

Enable Custom window tittle, then open your client and look at your title you've chosen.

"Testing//ro.hangame.com/login/loginstep..."

**Expected behavior**

It should only shows the custom title you've chosen.

**Additional Details (Complete all relevant items below)**

 - Hexed used: 2010-07-30, 2013-12-30, 2014-03-05.
- Windows 10
- Hercules Emulator

**Comment by Neo-Mind** [comment]
@cassioronchetti Check it now.

**Comment by cassioronchetti** [comment]
Fixed!
