### ISSUE TITLE
[BUG] Remove Swap Button

### ISSUE THREAD

**Issue by Samuel23** [Neo-Mind/WARP#20]
**Describe the bug**
Adding this patch leads to game crash at costume area
Still using: 2019-03-22aRagexe

**To Reproduce**
I can open my alt + Q and see equips and title area, but when costume area is selected, it crashes

Tested with both no equips and with equips

here is crash log: https://pastebin.com/5mixDD60

**Expected behavior**
Should not crash

In Nemo, same client, no crash

**Screenshots**
![](https://i.imgur.com/TpCkrJp.png)

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 - Tool Feature
 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by Neo-Mind** [comment]
Pushed the fix, please check and let me know.

**Comment by Neo-Mind** [comment]
@Samuel23 please confirm so that I can close this one.

**Comment by Samuel23** [comment]
@Neo-Mind Sorry for the late reply, got busy and I got new errors with other diffs thus it made hard for me to test this, but I can confirm that it was fixed with the latest patch. Thank you!
