### ISSUE TITLE
[BUG] Read iconstateimginfo is broken

### ISSUE THREAD

**Issue by Gardosen** [Neo-Mind/WARP#21]
**Describe the bug**
IF you enable the patch to read the iconstates from the lub file, only a handful of them will show up. 

example 

visible:
silence

not visible:
- concentration
- blessing
- agi up
- potions

**To Reproduce**
1. give yourself agi, bless or use a Concentration, Berserk or Awakening Potion when this patch is applied

**Expected behavior**
All states should show up

**Screenshots**
not really possible to show something here ^^

**Additional Details (Complete all relevant items below)**
I used the patch on a 2019-06-05-KRagexe.exe

**Comment by Neo-Mind** [comment]
Patch is working fine. 
Only problem, I found is that the stateiconimginfo.lub do not have icon file name entries for those skills.

**Comment by Neo-Mind** [comment]
Closing this since it's not really patch issue .
