### ISSUE TITLE
[FEATURE] Load/Save Patch Selection

### ISSUE THREAD

**Issue by Gardosen** [Neo-Mind/WARP#22]
**Is your feature request related to a problem? Please describe.**
Currently the only way how you can patch an exe with the same patches like in a previous session is by using the file PreviousSession.yml

if you wanna test specific features you have to make a copy of this file, and manually replace PreviousSession with the backuped version when you wanna go back to a previous version which is not the last one.

**Describe the solution you'd like**
implement 2 buttons
1. Load Custom File
2. Save Session As...

**Comment by Neo-Mind** [comment]
There is already an option to Load & Save Session files in the left drawer (Click the button on top left or you can swipe from the left edge).


![Left_Drawer](https://user-images.githubusercontent.com/4068357/117994521-3dcbdb80-b35e-11eb-8b33-5cc7f416d4d1.PNG)
