### ISSUE TITLE
[FEATURE] Add patch GvG Damage

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#23]
**Is your feature request related to a problem? Please describe.**
Recently a patch was added to NEMO that can see the damage on GvG maps, it would be very good to implement WARP as well.

**Describe the solution you'd like**
Patch NEMO: https://gitlab.com/4144/Nemo/-/blob/master/Patches/EnableGvGDamage.qs
By. **4144** & **X-EcutiOnner**

**Comment by Neo-Mind** [comment]
Patch has been added in latest commit @RagnaWay

**Comment by RagnaWay** [comment]
Working 
![image](https://user-images.githubusercontent.com/53480357/120560238-c0354180-c3d8-11eb-8c49-62945a944977.png)

**Comment by Neo-Mind** [comment]
Ok gr8.
