### ISSUE TITLE
[FEATURE] Add patch Fix Arrows Charset

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#24]
**Is your feature request related to a problem? Please describe.**
Fix Arrows Charset in Hotkey Setting UI wrong display for ASCII Langtype

Before
![image](https://gitlab.com/4144/Nemo/uploads/48adb2c04ba0b2f0e38dcd4fbb133786/image.png)

After
![image](https://gitlab.com/4144/Nemo/uploads/cb1040a018a2139e08f1b47f4b631174/image.png)

**Describe the solution you'd like**
Patch NEMO: https://gitlab.com/4144/Nemo/-/blob/master/Patches/FixArrowsCharset.qs
By. **X-EcutiOnner**

**Comment by Neo-Mind** [comment]
Patch has been added in latest commit @RagnaWay

**Comment by RagnaWay** [comment]
Not working 
![image](https://user-images.githubusercontent.com/53480357/120558430-d2fa4700-c3d5-11eb-901d-df148447d9f2.png)

**Comment by Neo-Mind** [comment]
What is the clientinfo setting you are using? Is it working with NEMO?
I crosschecked the changes made in 2021 client and they are identical.

**Comment by RagnaWay** [comment]
2021-01-07 langtype 12

**Comment by Neo-Mind** [comment]
@RagnaWay Check it now. I added the best approximate symbol possible within the ASCII table

**Comment by RagnaWay** [comment]
haha weird, but it worked.
![image](https://user-images.githubusercontent.com/53480357/121435427-3e539400-c955-11eb-862b-9f37f0017833.png)

**Comment by Neo-Mind** [comment]
Alright I am closing this then
