### ISSUE TITLE
[FEATURE] Enable Custom Player Skills

### ISSUE THREAD

**Issue by vBrenth** [Neo-Mind/WARP#25]
**Is your feature request related to a problem? Please describe.**
No, I'm using the custom Job Patch so this patch is needed :)

**Comment by Neo-Mind** [comment]
Added in local. Will be pushed next.

**Comment by Neo-Mind** [comment]
Patch has been added along with the other 2 Enable Custom Skills patches. Check it @vBrenth

**Comment by Neo-Mind** [comment]
Closing this for now.
