### ISSUE TITLE
[BUG] Custom Walk Delay doesn't apply

### ISSUE THREAD

**Issue by Everade** [Neo-Mind/WARP#26]
**Describe the bug**
Custom Walk Delay doesn't show any effect ingame.
Despite of what i set it to, the delay stays official.

**To Reproduce**
1. Apply the patch "Custom Walk Delay" and set it to something low (100 for example)
2. Go ingame and walk around quickly (left to right)
3. The delay of being able to change direction persists, despite the patch being applied.

**Expected behavior**
Apply the patch properly to take effect.
When testing ingame, changing directions with a delay of 100 (equal to 100ms) should be basically instant with every click.

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 Custom Walk Delay (WalkDelay.qis)
 - Client Version
 2021-01-07aRagexeRE
 - WARP Build Date
  c33d281fdc4847584a4e52167bccc60f077b2bfa
- OS
 Win 10
 
 **The current patch from NEMO works to set a custom walk delay value for 2021-01-07aRagexeRE.**

**Comment by Neo-Mind** [comment]
Fixed in latest commit. Please check @Everade

**Comment by Everade** [comment]
Thanks for the fix, works perfectly fine :)

**Comment by Neo-Mind** [comment]
gr8
