### ISSUE TITLE
[BUG] Increase VIEWID

### ISSUE THREAD

**Issue by Samuel23** [Neo-Mind/WARP#27]
**Describe the bug**
Any viewID above 5999 results to crash
Client used: 2019-03-22 Ragexe

**To Reproduce**
when Increase Headgear ViewID Limit is applied

I tried to increase at 64000 as said in the max value can be
I tried 32000
I even tried 10000

Then from 10000 downwards I tried which value where it will not crash and found 5999 is the ceiling

Here is crash log: https://bit.ly/3fW7AsC

**Expected behavior**
It should not crash

**Screenshots**

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name Increase Headgear ViewID Limit
 - Tool Feature
 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by Neo-Mind** [comment]
Is it crashing while opening itself? or when you do something specific?

I tried the patch at my end and I did not see any crash while opening. But I did see another peculiar behavior though.

**Comment by Samuel23** [comment]
Just equipping any item with view id above 5999 crashes me, that's why i was not able to test right away the other patch as I have to turn off my custom items

**Comment by Neo-Mind** [comment]
well I just added a new hat with view id 7200 and no crash. So I am not sure what is happening.
![Aqua_snip](https://user-images.githubusercontent.com/4068357/120263846-27100900-c2ba-11eb-8265-740cab545a19.PNG)

Do you have that many items in your server or you are just adding few items with higher ids?

**Comment by Samuel23** [comment]
Hmm I could give you the session file I used if you want to, because maybe in combination with other patch?

I'm using the same patches with nemo and the only difference is the custom job patch enabled in warp as it's not available in nemo for client 2019

Well I'm just testing the higher limits

**Comment by Neo-Mind** [comment]
@Samuel23 Yea that would be helpful.

**Comment by Neo-Mind** [comment]
I tried along with Custom Job patch but still no crash. Please share the session file either here or in Discord.

**Comment by Neo-Mind** [comment]
Not seeing the bug. If it still persists then reopen the ticket.
