### ISSUE TITLE
[BUG] Close cutin on Esc key - Crash

### ISSUE THREAD

**Issue by Everade** [Neo-Mind/WARP#28]
**Describe the bug**
Client crashes if pressing ESC while a cutin is opened.

**To Reproduce**
1. Apply the patch "Close cutin on Esc key"
2. Go ingame and trigger a cutin.
3. Left click the cutin to be sure that it's selected
4. Press ESC to trigger the crash

**Expected behavior**
By pressing ESC, the cutin should close instead.

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 Close cutin on Esc key (CloseCutinOnEsc.qjs)
 - Client Version
 2021-01-07aRagexeRE
 - WARP Build Date
 c33d281fdc4847584a4e52167bccc60f077b2bfa
- OS
 Win 10

**Comment by Neo-Mind** [comment]
Fixed the issue in local. Will be pushed in next commit soon.

**Comment by Neo-Mind** [comment]
Patch has been fixed in latest commit. Please check @Everade

**Comment by Everade** [comment]
Not sure how the patch worked on older clients because i've never had this functioning in the first place.

It now closes Cutins successfully, however at the same time it still open the Game Settings menu which is a little annoying.
I can only guess that's normal.

Eitherway, it doesn't crash anymore and it kinda works 🚨

**Comment by Neo-Mind** [comment]
ok i am closing it then.
