### ISSUE TITLE
Client Crashing [BUG]

### ISSUE THREAD

**Issue by cassioronchetti** [Neo-Mind/WARP#3]
**Describe the bug**
The client is crashing at login screen.

**To Reproduce**
1 - Diff the Hexed only using the reccomended patches.
2 - Open your client. (It show the error "ServiceType error")
3 - When you press enter after the Service Screen it will close your client at login screen.

**Expected behavior**
Show login screen to type your account and password to acess your server.

**Additional Details (Complete all relevant items below)**
 - Hexed used : 2013-12-30aRagexe // 2017-06-14 bRagexeRE
- Windows 10
 - Hercules Emulator

**Comment by cassioronchetti** [comment]
2010-07-30 works fine, but all the new clients I've tried crashes at login screen.

**Comment by Neo-Mind** [comment]
I have made some fixes. Please try it now.

**Comment by cassioronchetti** [comment]
Both Fixed! Now I am able to connect to server using both clients!
Congratulations Neo! You Rock!!!
