### ISSUE TITLE
[BUG] Ignore Palette Errors 

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#31]
**Describe the bug**
It was applying and working, and now it stopped working, it doesn't apply.
Tested in client 2021-01-07 on lasted WARP git

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/120560320-e22ec400-c3d8-11eb-9fb0-77ef992633bf.png)

**Comment by RagnaWay** [comment]
Solved! The error only happens when you first apply the patch "Ignore Resource Errors" and then the "Ignore Palette Errors"
![image](https://user-images.githubusercontent.com/53480357/120562300-836b4980-c3dc-11eb-8afc-a682cd16da6e.png)
however if you activate first the "Ignore Palette Errors" and then the "Ignore Resource Errors" then it works.
![image](https://user-images.githubusercontent.com/53480357/120562332-9251fc00-c3dc-11eb-8a13-96e4ac59924d.png)

**Comment by Neo-Mind** [comment]
It is not an error. 
If you select Ignore Resource Errors, then palette errors are also ignored, so you don't need to select the separate patch.
