### ISSUE TITLE
NewButtonVisibility patch is broken on newer clients.

### ISSUE THREAD

**Issue by k1ngJ** [Neo-Mind/WARP#32]
**Describe the bug**
NewButtonVisibility patch is broken on newer clients.
In this case, I'm using 2021-01-07a ragexeRE.

**To Reproduce**
Try to hide some buttons on the client.

**Expected behavior**
It should hide the specific buttons.

**Comment by Neo-Mind** [comment]
Fixed in local. Will be pushed out soon.

**Comment by Neo-Mind** [comment]
Update has been pushed. Check it @k1ngJ

**Comment by k1ngJ** [comment]
Works perfectly fine now on 2021-01-07a ragexeRE. Thanks.
