### ISSUE TITLE
[BUG] 1st and 2nd Login Background Patch

### ISSUE THREAD

**Issue by MrKeiKun** [Neo-Mind/WARP#33]
**Describe the bug**
Patches `Only 1st and 2nd Login Background` patch patches fine but it never enforces what it should do, it still loads other login background.

**To Reproduce**
1. Have the 12 files, `t1_¹è°æ1-1.bmp`-`t1_¹è°æ3-4.bmp` or `t2_¹è°æ1-1.bmp`-`t2_¹è°æ3-4.bmp` inside `data\texture\À¯ÀúÀÎÅÍÆäÀÌ½º`.
2. Use client `ragexe 2019-05-30a`
3. Patch it with `Only 1st Login Background` or `Only 2nd Login Background` as well as `Read Data Folder First`
4. Test it

**Expected behavior**
Display the correct login background depending on the patch.

**Comment by Neo-Mind** [comment]
Fixed in local (to the best of my belief). Will be pushed out soon.

**Comment by Neo-Mind** [comment]
Update has been pushed. Check it @MrKeiKun . Hopefully problem is solved.

**Comment by MrKeiKun** [comment]
`Second Login` works though `First Login` fails even `t1_` exist.

EDIT:

On second thought, on reading the patch, it should be `t_` and `t2_`. With that `First Login` and `Second Login` BG patches now works. <3
