### ISSUE TITLE
[FEATURE] Opening To Service Select

### ISSUE THREAD

**Issue by vBrenth** [Neo-Mind/WARP#35]
**Is your feature request related to a problem? Please describe.**
Well latest client have this "Opening" button if you use WARP its quite useless unless there is this opening to service select.

**Comment by Neo-Mind** [comment]
Added in local. Will be pushed out soon.

**Comment by Neo-Mind** [comment]
Patch has been added. Check it @vBrenth

**Comment by Neo-Mind** [comment]
Shall I close this?

**Comment by vBrenth** [comment]
Working
