### ISSUE TITLE
[FEATURE] Restore Songs Effect

### ISSUE THREAD

**Issue by vBrenth** [Neo-Mind/WARP#36]
**Is your feature request related to a problem? Please describe.**
Restore Songs ground effect from NEMO. It gets removed from 2019+ client onwards.

**Comment by Neo-Mind** [comment]
So 2018 clients won't need it right?

**Comment by vBrenth** [comment]
Yes, Only 2019, I also hope that you can reverse Sonic Blow and Vulcan Arrow effect.

**Comment by Neo-Mind** [comment]
I added the patch in local, but I am not sure why it's called 'restore songs effect' though.
To restore Sonic Blow & Vulcan Arrow effects, i need to know their IDs.

**Comment by vBrenth** [comment]
You mean Skill ID or client related ID (if client related) have no idea XD

**Comment by Neo-Mind** [comment]
Added the patch. Check it @vBrenth

**Comment by Neo-Mind** [comment]
Shall I close this?

**Comment by vBrenth** [comment]
Working

**Comment by vBrenth** [comment]
Working!
