### ISSUE TITLE
[FEATURE] Homun Auto Attack AI

### ISSUE THREAD

**Issue by MrKeiKun** [Neo-Mind/WARP#38]
**Is your feature request related to a problem? Please describe.**
Newer clients seems to fail on doing Homun Auto Attack. Such patch should be helpful.

**Comment by Neo-Mind** [comment]
Added in local. Will be pushed soon.

**Comment by Everade** [comment]
> **Is your feature request related to a problem? Please describe.**
> Newer clients seems to fail on doing Homun Auto Attack. Such patch should be helpful.

There has been a period in which auto-attack was disabled. However kRO reverted that change back in September 2020. So the latest clients should work just fine using custom AI with auto-attacks.

So which client dates exactly are you refering to? 2018-2020?

**Comment by Neo-Mind** [comment]
Changes have been pushed. Have a look 😄

**Comment by Neo-Mind** [comment]
@MrKeiKun hope you checked.

**Comment by MrKeiKun** [comment]
works like charm.. <3
