### ISSUE TITLE
[BUG] Camera Angle

### ISSUE THREAD

**Issue by MrKeiKun** [Neo-Mind/WARP#39]
**Describe the bug**
There seems to be a bug on all increase camera angle. Testing each one of them seems to show same minimum angle it can reach. 

**Additional Details (Complete all relevant items below)**
 - Client Date: 2019-05-30
 - Client Type: Ragexe

**Comment by Neo-Mind** [comment]
Check and let me know

**Comment by MrKeiKun** [comment]
yeah will gonna close this, mouse scroll can somewhat do angle to but never reaches the lowest angle for some reason.
