### ISSUE TITLE
GRF Encryption - File Not Found [BUG]

### ISSUE THREAD

**Issue by cassioronchetti** [Neo-Mind/WARP#4]
**Describe the bug**

When open your client. it will pop up a message saying "GRF Encryption -  File not Found - The client executable is invalid. Encryption feature will be disabled. Error code: 0x02."

**To Reproduce**

1. Diff your client using2017-06-14bRagexeRE using only the recommended patches...
2. Open your client and it will show a message error "GRF Encryption -  File not Found - The client executable is invalid. Encryption feature will be disabled. Error code: 0x02."

**Expected behavior**
Open your client without showing error.

**Additional Details (Complete all relevant items below)**

 - HEXED - 2017-06-14

**Comment by cassioronchetti** [comment]
I also tried to diff the client with the patches to Ignore Missing lua, Palletes,  Ressource error and Disable Packet Encryption but the error still persists.

**Comment by Neo-Mind** [comment]
Are the issues still present?

**Comment by admkakaroto** [comment]
@Neo-Mind Unfortunately yes, the client is unable to read the graphics.

**Comment by functor-x** [comment]
> 2\. Open your client and it will show a message error "GRF Encryption -  File not Found - The client executable is invalid. Encryption feature will be disabled. Error code: 0x02."

It isn't related to WARP. It means that GRF Editor's resource decryption dll(as usual "cps.dll") is bound to a specific EXE file name. If you change it without re-creation "cps.dll" - you will get this error.

**Comment by Neo-Mind** [comment]
Shall I close this then?

**Comment by cassioronchetti** [comment]
Yes, I think so
