### ISSUE TITLE
[BUG] Scream/Frostjoke not reading their text file

### ISSUE THREAD

**Issue by MrKeiKun** [Neo-Mind/WARP#40]
**Describe the bug**
Both `data\ba_frostjoke.txt` and `data\dc_scream.txt` exist yet client seems not reading the file. I'm not sure if this is a Client Bug or a Feature Request though.

**Additional Details (Complete all relevant items below)**
 - Client Date: 2019-05-30
 - Client Type: Ragexe

**Comment by Neo-Mind** [comment]
Well it is definitely reading the file but I am seeing all the wrong text.
![image](https://user-images.githubusercontent.com/4068357/124819725-3c97e300-df8a-11eb-932c-a4ccec0f8c87.png)

**Comment by MrKeiKun** [comment]
![image](https://user-images.githubusercontent.com/4362134/124886289-abb31d00-e006-11eb-9b1d-e8c57e5f77d5.png)
~~wait why mine is empty, i'm using langtype 1 :(~~

EDIT:
importing both scream and frostjoke file seems to fix this problem, really odd though
