### ISSUE TITLE
[FEATURE] Sakray - Enable Account Mails

### ISSUE THREAD

**Issue by Everade** [Neo-Mind/WARP#41]
**Is your feature request related to a problem? Please describe.**
Sakray clients have the Account-based "Notice" mailbox in RodEx disabled, so players can't access their account mails on their test server.
However that also means that if we use Sakray clients, we're entirely missing out on this feature because it can't be selected client-side.

**Describe the solution you'd like**
Compare base with sakray client, to create a patch that enables the ability to select the RodEx "Notice" Mailbox on Sakray clients.

**Additional context**
The translation of the mailbox is mostly refered to "Notice" or "Bulletin".
![image](https://user-images.githubusercontent.com/12261601/121807014-95f24800-cc52-11eb-82b4-154cafb9bcee.png)

**Comment by Neo-Mind** [comment]
Patch has been added. Check it out.

**Comment by Balferian** [comment]
> Patch has been added. Check it out.

Patch don`t work with 2021-11-17Ragexe
![image](https://user-images.githubusercontent.com/16213511/156820925-f4ab6221-be95-43fe-884d-146540f01d6b.png)

**Comment by Neo-Mind** [comment]
yea my bad. Check now.

**Comment by Balferian** [comment]
Excellent!
![image](https://user-images.githubusercontent.com/16213511/156824512-cbf99488-c1c5-461f-810d-9bcb962278d5.png)
Thanks =) Great job!

**Comment by Neo-Mind** [comment]
Closing this.
