### ISSUE TITLE
[BUG] PR_SUFFRAGIUM is missing from SkillType.lub

### ISSUE THREAD

**Issue by Daegaladh** [Neo-Mind/WARP#42]
**Describe the bug**
Suffragium is missing from SkillType.lub, so when enabling Custom Skill patches players cannot target other players without pressing shift.

**To Reproduce**
1. Custom Player Skill patch
2. Use Suffragium on a player or yourself (depends on pre-re or re mode)
3. You can't target players or yourself without pressing shift

**Expected behavior**
You should be able to target players without pressing shift.

**Screenshots**
N/A

**Additional Details (Complete all relevant items below)**

**Comment by Neo-Mind** [comment]
Will adding it to the list alone fix the issue?
I haven't tried it yet, but I have added the skill to the list anyways.

**Comment by Daegaladh** [comment]
> Will adding it to the list alone fix the issue? I haven't tried it yet, but I have added the skill to the list anyways.

Yeah, just needs to be added.

**Comment by Neo-Mind** [comment]
@Daegaladh Shall I close this ?

**Comment by Daegaladh** [comment]
Yeah, I'll close it myself 👍
