### ISSUE TITLE
Shared body palettes patch not working with costumes.

### ISSUE THREAD

**Issue by raiken-mf** [Neo-Mind/WARP#43]
Shared body palettes patch doesn't work on 2020-04-01b with costumes higher number than bodystyle 0.
(1, 2 or higher)

Result is a fatal error.

**Comment by Neo-Mind** [comment]
I am not seeing crash. Do you have the palette in the correct folder?
It should be **_"data\palette\¸ö\costume\_1\body\_\<colornum>\_\<stylenum>.pal"_**

**Comment by raiken-mf** [comment]
OH! That would make sense.. so palettes need a subfolder.. Case can be closed.

**Comment by Neo-Mind** [comment]
slight correction in the path. Markdown format ate an underscore /swt
