### ISSUE TITLE
[BUG] Increase Zoom Out Max

### ISSUE THREAD

**Issue by lukasrmattos** [Neo-Mind/WARP#44]
**Describe the bug**
When this patch is active, client zoom in distorts sprites. The higher the % zoom out, the greater the distortion

**To Reproduce**
Select any patch that increase zoom out.

**Expected behavior**
Game sprites must not distort when zooming in.

**Screenshots**
Without Any Zoom Out:
![image](https://user-images.githubusercontent.com/28408973/122602021-89059800-d048-11eb-910e-e43f474e6f79.png)

With Zoom Out Max apply:
![image](https://user-images.githubusercontent.com/28408973/122602062-9753b400-d048-11eb-8166-e0708d1c729a.png)

**Additional Details (Complete all relevant items below)**
 - 2018-06-21aRagexeRE
 - You can see a conversation about it in this issue https://gitlab.com/4144/Nemo/-/issues/103

**Comment by Neo-Mind** [comment]
@lukasrmattos I know u tried it and had issues.
 Perhaps some one else can also check it to see if it's finally fixed.

**Comment by Aruar** [comment]
> @lukasrmattos I know u tried it and had issues. Perhaps some one else can also check it to see if it's finally fixed.

Hi Neo. It hasn't been fixed. The character gets twisted. 

no zoom
![image](https://user-images.githubusercontent.com/19565165/151019413-29cde9cf-86f1-46a1-a34d-f2bfd2e84d31.png)

with the zoom
![image](https://user-images.githubusercontent.com/19565165/151019538-61cac68f-ad87-42bc-9d20-772a925530c5.png)

**Comment by Neo-Mind** [comment]
Can you check it now

**Comment by Neo-Mind** [comment]
@Aruar @lukasrmattos 
Is it ok now?

**Comment by Neo-Mind** [comment]
I am closing this. In case the issue still persists, please reopen the issue
