### ISSUE TITLE
[FEATURE] Show damage in woe

### ISSUE THREAD

**Issue by marcosbucarte** [Neo-Mind/WARP#49]
When the hide_woe_dmg setting is enabled from the server side, the client only shows damage as a value of 1.

Would it have the possibility to show the real value?

**Comment by CairoLee** [comment]
I don't think this feature is possible. Because the server will not return the real damage to the client. What ever you do, the client will not know what number can show...

**Comment by Neo-Mind** [comment]
As @CairoLee  stated, the setting works by not sending the real damage value to the client.
Hence, the client cannot show the damage.

Closing this since it cannot be done.
