### ISSUE TITLE
[FEATURE] Add colors to items

### ISSUE THREAD

**Issue by marcosbucarte** [Neo-Mind/WARP#50]
Suggestion for adding lua file to apply colors to items, example of lua configuration

`[2820] = 0xFF6600 // Orange`

![](https://gitlab.com/4144/Nemo/uploads/0e44715fc93a466f53d7fd4805ce73df/nWq7e.jpg)

**Comment by Neo-Mind** [comment]
I had done this one sometime back for NEMO but as a private patch.
I see 2 options currently:
   1) It will remain a special paid patch.
   2) It will be part of a donation goal package (along with other in demand patches). This way it will become an official patch.

At present, I haven't decided on which path to take.

**Comment by Neo-Mind** [comment]
I have made it a premium patch.

https://neo-mind.github.io/WARP/ItemNameColorLua
