### ISSUE TITLE
[BUG] NoMultiWindow breaks client

### ISSUE THREAD

**Issue by Everade** [Neo-Mind/WARP#52]
**Describe the bug**
The client won't start any longer with activated patch "Disable multiple windows".

**To Reproduce**
1. Test with 2021-01-07aRagexeRE
2. Apply patch "Disable multiple windows"
3. The client won't start any longer.

**Expected behavior**
Run the client.

**Additional Details (Complete all relevant items below)**
 - Patch name
   NoMultiWindow
 - Build Dates affected
   1.4
 - OS
   win64
 - Any other details relevant to the problem context
   2021-01-07aRagexeRE (loaded date 20201229)

**Comment by Neo-Mind** [comment]
Check now.

**Comment by Everade** [comment]
"Load Source" now immediately triggers a Script Error.
I cannot load any .exe

**Comment by Everade** [comment]
Works now, thank you!
