### ISSUE TITLE
[BUG] Customize OngoingQuestInfoList & RecommendedQuestInfoList

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#54]
**Describe the bug**
These two functions in the latest WARP is not working properly, when I try to rename the game it fails to open. Making mistakes in lubs. Tested with the client 2021-01-07

**Comment by Neo-Mind** [comment]
Are you sure the new lub files are available in the game directory?

Both of these files cannot be picked up from GRF.

**Comment by RagnaWay** [comment]
Yes... everyone is on System/
I did it like this:
**RecommendedQuestInfoList_Sakray.lub > QuestInfo.lub
OngoingQuestInfoList_Sakray.lub > Quest.lub**
and when you open the game both give lubs error.

**Comment by Neo-Mind** [comment]
Hmm I am not able to see the issue.

Hope you didn't suffix the `.lub` while setting the file name.
Also you need the prefix `system\`

**Comment by RagnaWay** [comment]
Ahhh the mistake was really that I put the .lub at the end of the patch. Sorry!
