### ISSUE TITLE
[BUG] 2019-06-19hRagexe MVP HP Bar size patch changes for all mobs not just MVP

### ISSUE THREAD

**Issue by plsfixrito** [Neo-Mind/WARP#57]
**Describe the bug**
The patch ResizeBossBar resizes the HP bar for all mobs not just MVP for client dated 2019-06-19hRagexe

**To Reproduce**
Enable ResizeBossBar in client date 2019-06-19hRagexe, hp bar will resize for all mobs not just MVPs

**Expected behavior**
Should only resize MVPs hp bar

**Screenshots**
https://puu.sh/HWPJz/7f8a7a5892.png

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 - Tool Feature
 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by plsfixrito** [comment]
Tested with 2020-04-01bRagexe client also, same issue. Using NEMO patch works for 2020-04-01bRagexe client.

**Comment by Neo-Mind** [comment]
Fixed in local . Will be pushed soon.

**Comment by Neo-Mind** [comment]
@plsfixrito Changes have been pushed. Please check now

**Comment by plsfixrito** [comment]
@Neo-Mind  I've tested the changes, now on 2020-04-1bRagexe it changes the HP bar size for normal monster only not MVP monsters.

**Comment by Neo-Mind** [comment]
Looks fine to me .
![image](https://user-images.githubusercontent.com/4068357/127265017-18682b34-efb2-4fb8-b5ba-54e76fa3e3ad.png)

**Comment by plsfixrito** [comment]
Yes, I tested again, it did change HP bar size for Mini-boss monsters, but not MVP monsters.
Tested with Atroce 1785
![image](https://user-images.githubusercontent.com/10469564/127266194-fc350bbd-1746-47cc-b576-4b59b8b818ee.png)
![image](https://user-images.githubusercontent.com/10469564/127266251-86ba242b-491c-4475-abe4-79550dd28696.png)
![image](https://user-images.githubusercontent.com/10469564/127266437-7db8bac6-b100-4a81-8391-55166c5ad94b.png)

**Comment by Neo-Mind** [comment]
ok i see it . will be fixed soon.

**Comment by Neo-Mind** [comment]
@plsfixrito I have split the patch into 3 - for Normal, Mini-Boss & Boss mobs respectively.
Now all of them can have different sized HP bars.
Check it out

**Comment by plsfixrito** [comment]
@Neo-Mind Tested with client 2020-04-01bRagexe seems to work perfectly fine now. Thank you.
