### ISSUE TITLE
[BUG] Custom Skill Homun / Mercenary / Player

### ISSUE THREAD

**Issue by SynchronyMaster** [Neo-Mind/WARP#58]
While using 2020-04-01 and 2019-06-26 fireball skill crash, or the player crash when loading the character on map (with the new WARP update).
I didn't proceed with further tests. I tried to update custom .lua file with all skills, but the error still happen.

**To Reproduce**
Patch the client and choose a character, use MG_FIREBALL on a mob

**Expected behavior**
Custom windows for player/mercenary/homun

**Comment by vBrenth** [comment]
When you apply the Custom Skill patch, and use any skills on latest client, it will just crash. Up for this.

**Comment by vBrenth** [comment]
@Neo-Mind Up! Still crashing,

**Comment by Neo-Mind** [comment]
Check now.

**Comment by vBrenth** [comment]
@Neo-Mind 
Client date at 2019-05-30aRagexeRE, 
Applied custom Skill Patch and just click any skills from skill tab, it crashes the client.

**Comment by Neo-Mind** [comment]
Fixed in local. Forgot to change back the active patch.
Will be pushing soon.

**Comment by Neo-Mind** [comment]
Check it now.

**Comment by Neo-Mind** [comment]
I am closing this. In case the issue still persists, please reopen the issue
