### ISSUE TITLE
[BUG] Missing Expected Token '}' in CustomExpBars.qjs

### ISSUE THREAD

**Issue by Gyakushinn** [Neo-Mind/WARP#6]
code = SetFillTargets(code, {
	 5 : UIW_TextOutA <<[ missing , ? ]
	11 : Exe.Phy2Vir(injectAddr + 5, CODE),
}, freeVir);

**Comment by Neo-Mind** [comment]
Yes, I saw this issue yesterday. Fixed in local. Will be pushing the commit soon.

**Comment by Gyakushinn** [comment]
thank you sir~
