### ISSUE TITLE
[BUG] Mob Info

### ISSUE THREAD

**Issue by pastragnarok** [Neo-Mind/WARP#60]
**Describe the bug**
On the server side conf/battle/monster.conf there is an option it has an option
// Display some mob info next to their name? (add as needed)
// (does not works on guardian or Emperium)
// 1: Display mob HP (Hp/MaxHp format)
// 2: Display mob HP (Percent of full life format)
// 4: Display mob's level
show_mob_info: 2

I choose 2 so that the HP of the mob will show a percentage of its life only but whatever you choose it only showing the monster name.

I am using 20190116 client I even tried 20180621 client but either of the two is still only show the mob name.

**Comment by Neo-Mind** [comment]
Check and confirmed that the issue is not from the tool but due to difference in the /showname setting.
