### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SynchronyMaster** [Neo-Mind/WARP#61]
Warp version (19/jun) open the game .exe with 'Enable custom jobs'. On thenewer version from (07/jul) the game do not open when you diff w/ custom jobs and open the .exe for client 2020-04-01

**To Reproduce**
Diff w enable custom job on client 2020-04-01

**Comment by Neo-Mind** [comment]
@SynchronyMaster  Works fine for me. Hope you have copied the lua files from the Inputs folder.
Maybe it got fixed in latest version. Can you try again?

**Comment by Neo-Mind** [comment]
Closing this since there has been no response. Please re-open if the issue persists.
