### ISSUE TITLE
[FEATURE] Ignore broadcast message from Resize Font.

### ISSUE THREAD

**Issue by ftakano** [Neo-Mind/WARP#64]
**Is your feature request related to a problem? Please describe.**
Well, after using the Resize Font diff, the announcement/broadcast message also resizes even you set the size in the script.
I think it is okay to ignore just the announcement from this Resize Font diff.
I set the broadcast font size by 20 in the script by the way.

**Describe the solution you'd like**
When using the Resize Font diff, the announcement/broadcast message should be ignored because you can set it on the script.

**Additional context**
Default font size
<img src="https://i.imgur.com/wmBSPE3.png"/>

Resize font size to 11
<img src="https://i.imgur.com/4GCO66W.png"/>

**Comment by Neo-Mind** [comment]
There is an alternate patch available now for changing the font size by adding an offset. 
Can you try that one?

For e.g. if you choose offset of 1 then existing size 10 will become 11 and size 20 will become 21
