### ISSUE TITLE
[BUG] Blank Space in Guild name

### ISSUE THREAD

**Issue by zakeph** [Neo-Mind/WARP#66]
**Describe the bug**
Patch 'Allow space in guild name' isn't working. 

**To Reproduce**
1. Create a Guild (for example pepe space)
2. Press OK will make it crash

**Screenshots**
Video: https://i.gyazo.com/d1c927bd7caea32631d38c552302538b.mp4
The crashlog: https://pastebin.com/dxU6GWcZ

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name: AllowSpaceInGuildName
 - Client Date: 2020-03-04
 - Client Type: aRagexeRE

**Comment by Neo-Mind** [comment]
Just tried it and I don't see any issues.
Can you try again with latest version? Maybe it got automatically fixed or something.

**Comment by RagnaWay** [comment]
Working for me
![image](https://user-images.githubusercontent.com/53480357/131149500-8060221d-6742-472c-8554-0dff7c43ad72.png)
![image](https://user-images.githubusercontent.com/53480357/131149300-f1ff210c-04af-41da-9139-52fbfe83ac73.png)

**Comment by Neo-Mind** [comment]
Closing this. Please re-open in case you see the issue again.
