### ISSUE TITLE
[BUG] Enable DNS Support

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#69]
**Describe the bug**
This "Recommended" patch reported error in the latest WARP to apply. Tested in 2021-01-07aRagexeRE

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/130950230-435f3b8e-d7c1-450f-acb6-d9a3d9b62cf6.png)

**Comment by Neo-Mind** [comment]
Yes saw it in local and fixed.
