### ISSUE TITLE
[BUG] Custom ClientInfo file patch won't work on 2018-06-21

### ISSUE THREAD

**Issue by SirHaziel** [Neo-Mind/WARP#7]
**Describe the bug**
Custom ClientInfo file patch won't work on 2018-06-21 RagexeRE.
The patch returns the error: "2nd reference missing".

**To Reproduce**
1. Go to 'Custom ClientInfo file'
2. Click on it and try to apply it to your client.
3. See error "2nd reference missing"

**Screenshots**
![WARP_0WXqto6dP3](https://user-images.githubusercontent.com/13502987/105180162-f7314780-5b08-11eb-9d66-a6869bab9554.png)

**Additional Details (Complete all relevant items below)**
 - 'Custom ClientInfo file' Patch
 - Windows 10
 - 2018-06-21 RagexeRE Client

**Comment by Neo-Mind** [comment]
hi, @SirHaziel let me know if the issue still persists or I can close this.
