### ISSUE TITLE
[BUG] Missing Patch "Customize MonsterSizeEffect"

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#70]
**Describe the bug**
After Patches.yml update this patch was removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/130951444-6f7fc667-9360-4299-9719-2d30c58f30f9.png)

**Comment by Neo-Mind** [comment]
Fixed in local. To be pushed soon.

**Comment by RagnaWay** [comment]
> Fixed in local. To be pushed soon.
https://github.com/Neo-Mind/WARP/commit/b4a32bfc4e65ef5b8df0a2985e41b539674c5aef
![image](https://user-images.githubusercontent.com/53480357/131028780-d5689238-8e73-49ab-a7ae-48dc283c4102.png)

**Comment by Neo-Mind** [comment]
yep, my mistake. thought i could override Functions, guess not. Fix has been pushed.

**Comment by RagnaWay** [comment]
Working. thanks!
