### ISSUE TITLE
[BUG] Enable Share Body / Head palettes

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#71]
**Describe the bug**
All patches have this error. 
**Enable share body palettes - male & female
Enable share body palettes -unisex
Enable share head palettes - male & female
Enable share head palettes - unisex**

Tested in 2021-01-07aRagexeRE

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/131101053-97b9b816-ca87-460c-97fd-1935fddba4f5.png)

**Comment by Neo-Mind** [comment]
Fixed.

**Comment by RagnaWay** [comment]
Thanks, working now!
