### ISSUE TITLE
[BUG] Show Buttons (New UI)

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#72]
**Describe the bug**
After WARP updates this patch is crashing the client when activating.
Lasted WARP
Client 2021-01-07aRagexeRE

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/131105749-8c9353fb-8093-4ec0-9327-5e3c6f50b851.png)

**Comment by Neo-Mind** [comment]
Fixed.

**Comment by RagnaWay** [comment]
Working!
