### ISSUE TITLE
[BUG] Enable Custom Jobs

### ISSUE THREAD

**Issue by xVaan** [Neo-Mind/WARP#73]
**Describe the bug**
Enable Custom Jobs causes the game won't open as #61.
Tested in **2020-04-01b** and **2019-06-26b**.

**To Reproduce**
1. Open WARP (rock-32 branch).
2. Load any of the mentioned RagExes.
3. Select Recommended patches plus Enable Custom Jobs.

**Expected behavior**
It doesn't throw any errors, the game just won't open.

**Additional Details**
 - Enable Custom Jobs
 - Build: WARP September 5th
 - OS: Windows 10

**Comment by RagnaWay** [comment]
I have tested it now and confirm this error. It's not really opening the client.

**Comment by Neo-Mind** [comment]
Found the issue and fixed in local. Will be pushed soon.

**Comment by Neo-Mind** [comment]
Please check now @xVaan @RagnaWay

**Comment by RagnaWay** [comment]
@Neo-Mind Working... client openning now!

but there still remains that old problem when changing class names, **Summoner** > **Invocador** ( bRO - Brazil ) . This happens with many other classes as well when you change the name. Most are named after Poring
![image](https://user-images.githubusercontent.com/53480357/132914385-ac2e12ac-16cf-4d8f-98d0-e110657e87e2.png)

**Comment by Balferian** [comment]
Found another one problem when use ACSI names.
2020-09-02b.
![image](https://user-images.githubusercontent.com/16213511/132949314-bd517eb4-8a7d-418a-8308-64784f44c126.png)

**Comment by RagnaWay** [comment]
It's working for me, @job 4 ( Novice / Noviço -> bRO - Brazil )  **Ç** is ASCII/ANSI. Check your langtype.
![image](https://user-images.githubusercontent.com/53480357/132949912-012b1720-b27d-47bf-bad6-32930e69ffcd.png)
![image](https://user-images.githubusercontent.com/53480357/132950041-8c7c7efb-b7d9-4fdc-8bce-a213e09819d5.png)

**Comment by Balferian** [comment]
I use langtype 14 (Russian)

**Comment by feltenc** [comment]
@RagnaWay how did you fixed the error with "poring" classes?

**Comment by RagnaWay** [comment]
> @RagnaWay how did you fixed the error with "poring" classes?

I didn't fix it, only a few names can be used, but most are Poring

**Comment by Neo-Mind** [comment]
I have started looking into this in detail now.

**Comment by RagnaWay** [comment]
> I have started looking into this in detail now.

[PCNames.zip](https://github.com/Neo-Mind/WARP/files/7272065/PCNames.zip)
This is mine that I use to translate the class names to Portuguese.

**Comment by Neo-Mind** [comment]
> [PCNames.zip](https://github.com/Neo-Mind/WARP/files/7272065/PCNames.zip) This is mine that I use to translate the class names to Portuguese.

@RagnaWay I see one issue. Currently the patch makes the client load all the names from LUA only.

Since you have kept the entries for only some of the names, all the remaining ids will end up with the default name i.e. Poring.

You need to :
> Keep all the other entries in the `PCNames, PCNames_F & PCNames_M` tables as well. If you only have 1 intended langtype then you can remove all the `LT_*` sub tables

OR

> Keep the original `PCNames, PCNames_F & PCNames_M` tables intact and only setup your name overrides inside `PCNames.LT_12 , PCNames_F.LT_12 and PCNames_M.LT_12` tables respectively. 

LT_12 stands for Langtype 12

@feltenc  @Balferian @xVaan Is everyone else making the lua file changes this way?

**Comment by Neo-Mind** [comment]
@feltenc @Balferian @RagnaWay @xVaan 
I have updated the Lua files (PCFuncs & PCImfs to be specific), please update the same in your areas. These should fix the other errors.

**Comment by holzenzZ** [comment]
> @feltenc @Balferian @RagnaWay @xVaan 
> I have updated the Lua files (PCFuncs & PCImfs to be specific), please update the same in your areas. These should fix the other errors.
> 
> 

This patch only update lua files right?. can i use without exe diff?

**Comment by RagnaWay** [comment]
@Neo-Mind Working now! thanks!

**Comment by Neo-Mind** [comment]
@poipioil The patch is still needed for the lua files to be loaded.
However, if you already have added it to an exe then no it doesn't need to be changed.

**Comment by feltenc** [comment]
Works like a charm @Neo-Mind. Thanks for the attention!
