### ISSUE TITLE
[BUG] Guild creation crash game with "Allow guild activities in clan"

### ISSUE THREAD

**Issue by Shaktohh** [Neo-Mind/WARP#75]
**Describe the bug**
Create a guild with UI with "Allow guild activities in clan"  patch
The client crash without create the guilde

Client 2020 07 15

**Comment by Neo-Mind** [comment]
@Shaktohh check it now.

**Comment by Shaktohh** [comment]
Hello @Neo-Mind, i'll check this week-end, i missed your previous message.

**Comment by Shaktohh** [comment]
Seems good thank you !
