### ISSUE TITLE
[BUG] DNS Support not working on 2020-04-01

### ISSUE THREAD

**Issue by SynchronyMaster** [Neo-Mind/WARP#77]
**Describe the bug**
I made all configurations on subnet and clientinfo.
When I use my external ip (189.5.7...). Both on server and clientinfo. I can login without problems. But when I use my no-ip (server.noip.ddns) on clientinfo, i can't login. It still works when I use no-ip on emulator and external ip (189...) on clientinfo, but when I change clientinfo to no-ip, the same on emulator/conf, it don't connect.

1. 2020-04-01b with no-ip adress

**Comment by DescendingSky** [comment]
Having exact same issue.
127.0.0.1 and external IP addresses connect instantly, but any no-ip host (tried the 3 I currently have) fails to connect. Nothing shows up in logserv.
Like OP, server is properly configured with no-ip hostname for servers and subnet.

**Comment by SQLoser** [comment]
Trying to use no-ip on my server and i'm getting the same issue as noted above.
I'm hosting the server in a dynamic ip enviroment and the no-ip solution is a must have, cause the ip changes from none to several times a day without much control.
Activated notifications on the fix for this bug.
Thanks in advance.

**Comment by Neo-Mind** [comment]
I dunno how accurate it would be if I setup no-ip from my end and test with that.

Can anyone of you share your no-ip either here or in a DM at Discord ( \_Neo_#7539 ) to debug this.

**Comment by Neo-Mind** [comment]
I have pushed an updated version of the patch . Please check it and let me know.

**Comment by DescendingSky** [comment]
tested again with the same hostname I was using before and the 2020-04-01 client, it is **working** now!
thank you very much for the quick reply and fix, I'll send the client to my friends so they can run the ultimate test now.

**Comment by SynchronyMaster** [comment]
Tested, working now.

**Comment by Neo-Mind** [comment]
Ok I am closing this one
