### ISSUE TITLE
[BUG] Increase Digit Display

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#8]
**Describe the bug**
Error when trying to apply the patch.
I tested with several customers 2020 and 2021 and none worked.

**To Reproduce**
![image](https://user-images.githubusercontent.com/53480357/106502573-4ed59880-64a3-11eb-9994-2b775c574e91.png)

**Comment by Neo-Mind** [comment]
My understanding is that this patch won't be required for recent clients.
I will check anyways to make sure.

**Comment by Neo-Mind** [comment]
I checked and looks like the Abbreviation with 'K' is present from 2019-06-xx clients onwards. 
But this also means some of the clients in 2019 will need an update.

**Comment by Neo-Mind** [comment]
Pushed the fixes. The patch is required only till May 2019 and it works for all those dates now.
Please check and let me know.

**Comment by Neo-Mind** [comment]
@RagnaWay please confirm so that I can close this one.

**Comment by RagnaWay** [comment]
> @RagnaWay please confirm so that I can close this one.

Client 2021 not show more this patch.

**Comment by Neo-Mind** [comment]
Yes because after 2019-05-xx, this patch is no longer necessary. Now, the client has started using 'k' suffix whenever the values go beyond 1000 . 

For e.g. 1604432 gets displayed as 1604k now.

**Comment by Neo-Mind** [comment]
@RagnaWay  Are you facing any issue before 2019-05-xx date ? If yes then I need to check on it.
Let me know otherwise I need to close this one.
