### ISSUE TITLE
[BUG] Enable proxy support

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#80]
**Describe the bug**
This patch is crashing the client after trying to login. ( Tested with latest WARP. )

**Screenshots**

![image](https://user-images.githubusercontent.com/53480357/139276726-40334e7a-9763-4f74-85d9-604e0bd1d360.png)
![image](https://user-images.githubusercontent.com/53480357/139276979-a086d67d-c3ff-4aed-a4d4-f2bfcf9c20f6.png)

**Comment by Neo-Mind** [comment]
Check it now @RagnaWay
