### ISSUE TITLE
[BUG] Disconnect to login window 2021-01-07aRagexeRE

### ISSUE THREAD

**Issue by feltenc** [Neo-Mind/WARP#81]
**Describe the bug**
The patch "Disconnect to login window" is not working on 20210107 hexed.

**To Reproduce**
1.  Try to use the patch and..
![image](https://user-images.githubusercontent.com/22537929/139906814-c37bd256-c672-4b38-b312-2ad41ae21470.png)

**Expected behavior**
It Should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/22537929/139907098-b9578c93-e051-4241-aa65-25e7a87779a1.png)

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name - Disconnect to Login Window
 - Tool Feature - WARP
 - Build Dates affected - 20210107aRagexeRE
 - OS - Any
 - Any other details relevant to the problem context - None

**Comment by Neo-Mind** [comment]
I haven't checked it in 2021-01-07RE yet. But my understanding is that this one is not needed most of the time. 
Sometimes the client show "Now logging out" and closes the client which needs to be fixed.

@feltenc  Is the client getting closed after showing the "Disconnected from Server" message as well now?

**Comment by feltenc** [comment]
Hello Mr @Neo-Mind .

The client is closing in all those situations;

- Using @autotrade command;
- When the map-server crashes;
- When the server shut down(and you are logged in).

As i think it should send the player to login screen.

**Comment by Neo-Mind** [comment]
@feltenc 
Try it now.

**Comment by Neo-Mind** [comment]
I am closing this. In case the issue still persists, please reopen the issue
