### ISSUE TITLE
[BUG] 2021-11-05 RagexeRE

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#82]
**Describe the bug**
With the release of the new 2021-11-xx clients, some diffs are having problem to be applied. Tested with the latest WARP and with the client ( http://nemo.herc.ws/downloads/2021-11-05_Ragexe_1636095152/ )

[Edit] > Some patches disappeared:
• Customize CheckAttendance lub
• Customize Iteminfo lub
• Customize MonsterSizeEffect lub

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/140572834-e9bd161a-152e-445c-a4e8-2b766f338f7d.png)
![image](https://user-images.githubusercontent.com/53480357/140572913-895aba79-29ea-4af0-a0a5-b0fdd72ef14d.png)
![image](https://user-images.githubusercontent.com/53480357/140572952-396149a9-44d9-4b6c-99fe-93e0302a1504.png)
![image](https://user-images.githubusercontent.com/53480357/140573020-9a4b58a4-21d9-4bb3-8390-820ae30e40e5.png)
![image](https://user-images.githubusercontent.com/53480357/140573040-2e2caa9d-ab17-4e0e-820d-319e00a3b5b1.png)

**Comment by Neo-Mind** [comment]
All of it has been fixed.
Translate taekwon patch is not needed anymore since the job name is retrieved from msgstringtable now.
