### ISSUE TITLE
[BUG] Draw Shield on Top | Client Crash | 2018-06-20eRagexeRE

### ISSUE THREAD

**Issue by waken22** [Neo-Mind/WARP#83]
**Describe the bug**
When i apply this patch "Draw Shield on Top" the client crash when the character is gonna be rendered (in map loading).

**To Reproduce**
1. Character Selection
2. Login with that char
3. Crash before the map loads

**Expected behavior**
To don't crash.

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name: Draw Shield on Top
 - OS : Windows 10
 - Client: 2018-06-20eRagexeRE

**Comment by Neo-Mind** [comment]
Check it now.

**Comment by Neo-Mind** [comment]
@waken22 Please check and confirm

**Comment by Neo-Mind** [comment]
I am closing this. In case the issue still persists, please reopen the issue
