### ISSUE TITLE
[BUG] Enable share head palettes - male & female/unisex Can't Load head_(number).pal

### ISSUE THREAD

**Issue by holzenzZ** [Neo-Mind/WARP#84]
**Describe the bug**
patched
Enable share head palettes - male & female
Enable share head palettes - unisex

can't not load file head_(number).pal it load old path

**To Reproduce**
1. Login
2. See error

**Expected behavior**
to load file  head_(number).pal

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name:  Enable share head palettes - male & female/Enable share head palettes - unisex
 - Client: 2021-01-07aRagexeRE
 - OS : Windows

**Comment by Neo-Mind** [comment]
are you sure about this? coz...it is working for me . 
I checked a higher hair style like 60 and 70 too just to make sure.

**Comment by Neo-Mind** [comment]
@poipioil  Please check and confirm.

**Comment by umarsaidhabibulloh** [comment]
I face the same problem.. using hair style: 3, hair color: 892, gender: female, class: shadow cross, client version 20211117
![image](https://user-images.githubusercontent.com/69049516/163678545-6d07cf78-c47e-46b8-8fc1-955aa0412cd4.png)
![image](https://user-images.githubusercontent.com/69049516/163678612-0610ecdf-bec1-4121-99ad-d79d3b579112.png)
![image](https://user-images.githubusercontent.com/69049516/163678636-f9e00079-c780-4a1b-bc9c-4186858e0089.png)

**Comment by Neo-Mind** [comment]
I see the issue now. The 65k hairstyle patch is overwriting the changes done by shared palette. I am working on it.

**Comment by Neo-Mind** [comment]
Fixed in local. Will be pushed soon.

**Comment by Neo-Mind** [comment]
Try it now

**Comment by Neo-Mind** [comment]
@umarsaidhabibulloh @AcDczZ can I assume you don't see the problem anymore?
I will be closing this tomorrow.
