### ISSUE TITLE
[BUG] Enable item preview is Cash Shop patch

### ISSUE THREAD

**Issue by lelouch22** [Neo-Mind/WARP#86]
After applying this patch to 2019-03-22aRagexe some of the items in the cash shop turned into unknown item and its cash value went insanely high. Also i tried applying this to 2020-04-01bRagexe but its still the same issue.

![weewescasdfasdasdasd](https://user-images.githubusercontent.com/4976551/146689397-848a5353-3eb6-474a-8a0f-fabf1b303b13.png)

**Comment by 4144** [comment]
@lelouch22 read information here about preview patch http://nemo.herc.ws/patches/ExtendCashShopPreview/#information

**Comment by lelouch22** [comment]
> @lelouch22 read information here about preview patch http://nemo.herc.ws/patches/ExtendCashShopPreview/#information

~~Btw so if it needs a emulator support does rA have this?~~
Oh nvm i found it...
https://github.com/rathena/rathena/blob/master/src/config/core.hpp#L84

**Comment by 4144** [comment]
yes ra have support too
