### ISSUE TITLE
[BUG] Customize MonsterSizeEffect lub in 2021-11-17aRagexeRE

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#88]
**Describe the bug**
the patch Customize MonsterSizeEffect lub is not appearing to be applied on the 2021-11-17aRagexeRE client, tested on the latest version of WARP

**Comment by JohnnyPlayy** [comment]
Up

**Comment by Neo-Mind** [comment]
Fixed in local . Will be updated soon.
