### ISSUE TITLE
[BUG] Missing Translation

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#89]
**Describe the bug**
Translation is missing from Stylist UI window, testing with client 2021-11-17

![image](https://user-images.githubusercontent.com/53480357/150530446-a87443ab-dd08-4e1b-81b1-064ff34bc607.png)

**Comment by Balferian** [comment]
_it's client side problem._
Oh, i think it's rA git, sorry😅

**Comment by llchrisll** [comment]
I think that's an hard coded text, like the previous "unmount" dropdown in ALT+Q window.
ANSI: `¿°»öÁ¦°Å`
Translates to this:
![image](https://user-images.githubusercontent.com/5730576/151339784-1a9efec9-f1bc-4fcc-9db8-f1052493d88d.png)
My Hex Editor found it here:
![image](https://user-images.githubusercontent.com/5730576/151340326-e6b6f033-ab6b-4cf3-abee-48f18ad5ed55.png)

**Comment by Neo-Mind** [comment]
Any idea which date onwards needs this one.

**Comment by llchrisll** [comment]
Well I guess anything since the Styling Shop was implemented xD.

**Comment by Lemongrass3110** [comment]
> Well I guess anything since the Styling Shop was implemented xD.

No this button was added later on.

**Comment by Neo-Mind** [comment]
Well i have added it in

**Comment by Neo-Mind** [comment]
@RagnaWay @llchrisll 
@Lemongrass3110 @Balferian 
Can any of you check if this has been fixed. I am going to set the start date to 20211100 onwards since anything older seems to be failing.

**Comment by RagnaWay** [comment]
> @RagnaWay @llchrisll @Lemongrass3110 @Balferian Can any of you check if this has been fixed. I am going to set the start date to 20211100 onwards since anything older seems to be failing.

Sorry... Working 100%

![image](https://user-images.githubusercontent.com/53480357/156440205-08f463c7-c022-472a-9a3a-d6de517bc031.png)
