### ISSUE TITLE
[BUG] Enable Font Height Limits and Customize Font Names patch

### ISSUE THREAD

**Issue by lelouch22** [Neo-Mind/WARP#92]
**Describe the bug**
The client auto closes when you run it. But if you use the default font size of 10 this won't occur.

**To Reproduce**
1. Enable Font Height Limits: Changing font size to 12 and above.
2. Customize Font Names: Changing font size to 11 and above.

**Additional Details (Complete all relevant items below)**
 - I'm using 2019-03-22aRagexe client.

**Comment by Neo-Mind** [comment]
No. 1 is fixed in local. Will be pushed soon.
For No.2 you are supposed to set the font name & not the size unless you meant a different patch name.

**Comment by Neo-Mind** [comment]
Try it now.

**Comment by Neo-Mind** [comment]
@lelouch22 Are the issues still present? 
I will be closing this tomorrow
