### ISSUE TITLE
[BUG] Fix homunculus attack AI patch disables the attack cursor on GVG maps

### ISSUE THREAD

**Issue by xVaan** [Neo-Mind/WARP#93]
**Describe the bug**
Fix homunculus attack AI patch disables the attack cursor on GVG maps.

**To Reproduce**
1. Build a client with Select Recommended + Fix hom attack AI.
2. Open two clients and warp to a GVG flagged map.
3. You won't be able to attack others players.

**Additional Details (Complete all relevant items below)**
 - Latest WARP build.
 - Tested in 2021-03-07 & 2021-11-03 Ragexe
 - OS: Windows 10

**Comment by Gyakushinn** [comment]
I'm Confirm
I also encountered this problem.

**Comment by Neo-Mind** [comment]
Pokye confirmed that this patch is not needed for 2021+ clients as homunculus auto-attack 
has been reactivated the on these dates. Hence i will be hiding the patch for the newer dates.
