### ISSUE TITLE
[BUG] Disable Game Guard on 2022-03-30_Ragexe

### ISSUE THREAD

**Issue by Lemongrass3110** [Neo-Mind/WARP#95]
**Describe the bug**
The diff Disable Game Guard is not working on 2022-03-30_Ragexe.

**To Reproduce**

1. Open WARP
2. Select your local copy of 2022-03-30_Ragexe
3. Load Source
4. Select the diff Disable Game Guard

**Expected behavior**
The diff should be working

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3517879/172438058-01826da9-a9bb-43fb-a4dd-87d455af0b8c.png)

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name
 - Tool Feature
 - Build Dates affected
 - OS
 - Any other details relevant to the problem context

**Comment by Neo-Mind** [comment]
umm I don't have access to that exe version

**Comment by Lemongrass3110** [comment]
Sent them to you on discord.

**Comment by Neo-Mind** [comment]
I have made some changes in local. Once it is pushed, please test it out.

**Comment by Neo-Mind** [comment]
Check now. well you already kind of did...

**Comment by Lemongrass3110** [comment]
Works perfectly fine! Thanks once again!

**Comment by Neo-Mind** [comment]
Alright I am closing this then.
