### ISSUE TITLE
[BUG] Summoner & Spirit Handler mount

### ISSUE THREAD

**Issue by Rushtic** [Neo-Mind/WARP#96]
**Describe the bug**

**To Reproduce**
1. Go to 'WARP, add custom jobs'

**Expected behavior**
Cart summoner & Spirit handler riding not shown

**Screenshots**
![image](https://user-images.githubusercontent.com/100025131/173286491-e13700d8-f4eb-4835-b2e7-d28a8b9a8ac2.png)

**Comment by Neo-Mind** [comment]
Fixed in local. Problem was in lua files not the patch itself. Will be pushed soon.

**Comment by Neo-Mind** [comment]
The lua files have been updated.

**Comment by Neo-Mind** [comment]
@Rushtic Hope you got a chance to test out the updated lua files.
I will be closing this tomorrow.

**Comment by Rushtic** [comment]
> @Rushtic Hope you got a chance to test out the updated lua files. I will be closing this tomorrow.

Its work perfectly. Thank you
