### ISSUE TITLE
[BUG]Enable Custom Shield can't open client.

### ISSUE THREAD

**Issue by hnomkeng** [Neo-Mind/WARP#97]
**Describe the bug**
Enable Custom Shield can't open client.

**To Reproduce**
1. Go to 'WARP, enable custom shields.'

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name 1.5.3
 - Client date 20211116

**Comment by Neo-Mind** [comment]
Fixed in local. Will be pushed out soon.

**Comment by Neo-Mind** [comment]
Try it now.

**Comment by Neo-Mind** [comment]
@hnomkeng Hope you are not facing any further bugs.
I will be closing this tomorrow.

**Comment by hnomkeng** [comment]
> @hnomkeng Hope you are not facing any further bugs.
> 
> I will be closing this tomorrow. 

fixed, thank you bro.
