### ISSUE TITLE
[BUG] Custom Jobs missing Soul Ascetic and Sky Emperor

### ISSUE THREAD

**Issue by Pokye** [Neo-Mind/WARP#98]
**Describe the bug**
Custom Jobs missing Soul Ascetic and Sky Emperor.
And error with mounts not appearing from Rune Knight's Summoner and Ferus.

**Comment by Neo-Mind** [comment]
The names have been fixed in local. Lua file was incomplete. Will be pushed soon.
As for the mounts I don't see any issue with rune knight or dragon knight.

**Comment by Neo-Mind** [comment]
The lua files have been updated.  Check it out

**Comment by Neo-Mind** [comment]
@Pokye Hope you started using the updated lua files.
I will be closing this tomorrow.

**Comment by Pokye** [comment]
Working 100% now. thanks
