### ISSUE TITLE
Error with Custom Icon

### ISSUE THREAD

**Issue by jbersamin** [Neo-Mind/WARP#99]
**Describe the bug**
I was trying to change the exe icon with 48x48 ico file but its not working.

Is there a proper guide on what to use, what kind of ico we will use?

**Comment by Neo-Mind** [comment]
At present the specs should be 32x32 8bpp.  But I am planning on updating the patch to make other sizes acceptable.

**Comment by Neo-Mind** [comment]
The patch has been updated to support all specs of icons now.
